package main

import "fmt"

// This file is this package's marker discipline (plan §36): every
// diagnostic-producing code path that runs anywhere reachable with
// credential bytes (the sanitizer, which is handed the raw JWT on stdin) or
// raw captured-PDU bytes (the recorder/proxy, the sanitizer, the compare/
// construct subcommands) is required to go through one of the fixed-shape
// constructors below rather than an ad hoc fmt.Errorf. Every constructor's
// format string is a fixed literal; the only interpolated values are safe
// classification data — operation labels, counts, lengths, filenames, and
// already-safe wrapped errors from this package's own bounded BER reader
// (never a raw byte slice or credential string). This mirrors
// internal/ldap's convention of logging only a short fixed internal reason
// literal instead of an underlying verifier/role-resolver error's own text
// (see internal/ldap/redaction_boundary_test.go's header comment).
//
// TestWireRecorderRedaction_MarkerNeverLogged is the regression proof: it
// feeds distinctive credential- and raw-PDU-shaped marker values through
// each of the six paths below (malformed frame, proxy error, sanitize zero
// match, sanitize multiple matches, invalid metadata, constructed-
// generation error) and asserts the resulting diagnostic text never
// contains any of those markers.

// errMalformedFrame reports a bounded-BER framing failure. context is
// always one of this file's own fixed literals; err is always this
// package's own classification error from ber.go (a tag/length mismatch or
// a generic I/O failure) or an os/io stdlib error — never a value built by
// formatting raw PDU bytes into an error string.
func errMalformedFrame(context string, err error) error {
	return fmt.Errorf("wirecapture: malformed frame (%s): %w", context, err)
}

// errProxy reports a forwarding/dial failure between the client and
// upstream connections. Never includes payload bytes — only the fixed
// context label and the underlying net/io error's own (payload-free) text.
func errProxy(context string, err error) error {
	return fmt.Errorf("wirecapture: proxy error (%s): %w", context, err)
}

// errSanitizeZeroMatch reports that the stdin-provided credential occurred
// zero times across every captured client PDU. Deliberately does not
// include the credential itself, nor any PDU content — only the fixed
// requirement text.
func errSanitizeZeroMatch() error {
	return fmt.Errorf("wirecapture: sanitize: credential occurred zero times across captured client PDUs (require exactly one, inside a Bind PDU)")
}

// errSanitizeMultipleMatches reports that the stdin-provided credential
// occurred more than once. count is a safe integer; never the credential or
// PDU content.
func errSanitizeMultipleMatches(count int) error {
	return fmt.Errorf("wirecapture: sanitize: credential occurred %d times across captured client PDUs (require exactly one, inside a Bind PDU)", count)
}

// errSanitizeNotInBind reports that the exactly-one occurrence found was
// outside the Bind PDU. filename is a safe on-disk name, never content.
func errSanitizeNotInBind(filename string) error {
	return fmt.Errorf("wirecapture: sanitize: credential's sole occurrence is in %s, not the Bind PDU", filename)
}

// errConnectionCountNotOne reports the N==1 session invariant failing
// (plan §21/§24). count is a safe integer.
func errConnectionCountNotOne(count int) error {
	return fmt.Errorf("wirecapture: refuse to proceed: %d connections recorded, require exactly 1 (never selecting one heuristically)", count)
}

// errInvalidMetadata reports a metadata (session.json/profile.json)
// validation failure. context and err are always safe (field names, counts,
// path fragments) — never raw JSON/BER content, per internal/wirefixture's
// own error-safety discipline that this file matches.
func errInvalidMetadata(context string, err error) error {
	return fmt.Errorf("wirecapture: invalid metadata (%s): %w", context, err)
}

// errConstructGeneration reports a constructed-fixture generation failure
// from internal/wirefixture's builder. Never includes generated bytes.
func errConstructGeneration(context string, err error) error {
	return fmt.Errorf("wirecapture: constructed-generation error (%s): %w", context, err)
}

// errProfileFlagMissing reports that a required profile-writing flag
// (plan §9/§26's sanitize --profile-out extension) was left empty. field
// is always one of profile.go's own fixed flag-name literals — never any
// flag *value* — so this can never echo caller-supplied content.
func errProfileFlagMissing(field string) error {
	return fmt.Errorf("wirecapture: profile: missing required %s", field)
}

// errProfileConfigHashSource reports that --config-file and --config-sha256
// were both supplied, or neither was, when writing profile.json. reason is
// always one of profile.go's own fixed literals; never file content.
func errProfileConfigHashSource(reason string) error {
	return fmt.Errorf("wirecapture: profile: %s (supply exactly one of --config-file or --config-sha256)", reason)
}

// errProfileDrift reports that a freshly built profile.json for a tracked
// line does not match (byte-for-byte, via the equal-Profile-value
// guarantee documented on WriteProfileFromInput) the profile.json already
// committed on disk for a prior session of the same line (plan §9/§26):
// this tool refuses to silently overwrite per-line provenance metadata.
// line is a safe, fixed classification value (e.g. "24.8"), never file
// content.
func errProfileDrift(line string) error {
	return fmt.Errorf(
		"wirecapture: profile: freshly built profile.json for line %q does not match the committed profile.json already on disk (refusing to overwrite; reconcile the source/tool inputs instead)",
		line)
}
